[IS-23-24] Lenguaje.Nivel 2
Codecr-ft/TurnoGen pull request #29
Opened 2024-02-21 16:37 UTC by maguilerafr

## Descripción de este PR: 
- En esta etapa (Nivel 2) hemos tenido como objetivo el de modelar los principales elementos extraídos de las HU, para que en las siguientes MS se pueda empezar a obtener un PMV útil.

## Issues que cierra:
 closes
- #48 
- #47 
- #36 
- #35 
- #34 
- #33 
- #32 
- #31 
- #30 
## Lista de comprobación

* [x] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [x] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

* [x] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [x] ¿Los issues representan un problema, y no una tarea?

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.
* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están relacionados con a una HU?
* [x] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [x] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2024-02-21 16:38 UTC, ZazRX8 submitted a review, later dismissed

2024-02-21 17:09 UTC, JJ commented
Recordad que tenéis que mantener este PR abierto y hacer PRs contra esta rama con cada issue.

2024-02-26 16:14 UTC, JJ commented
Todavía no podéis aprobarlo, hasta que no hayáis fusionado todos los PRs

2024-02-27 19:11 UTC, JJ reviewed
Algunos comentarios sobre el estado actual.

2024-02-27 19:11 UTC, JJ commented on TurnoGen/Codigo.md
> +# Nuevo directorio para subir código
Este fichero igual podríais quitarlo ya.

2024-02-27 19:11 UTC, JJ commented on TurnoGen/Employee.py
> +class Employee:
Recordad lo que os he dicho sobre mayúsculas en los ficheros. Como esto lo vas a tener que modificar, hazlo en el PR correspondiente.

2024-02-27 19:11 UTC, JJ commented on is.yaml
> +entidad: src/Recordatorio.js
Este fichero ya no existe, actualizadlo con lo que sea realmente una entidad según DDD.

2024-02-27 19:11 UTC, JJ commented on src/Recordatorio.js
> +
Por lo mismo, lo podéis borrar (no hace falta un PR)

2024-03-04 19:39 UTC, maguilerafr commented
@JJ revise esto

2024-03-04 19:40 UTC, JJ commented
> @JJ listo para revisión

En este cuerpo del PR tenéis que poner
1. Cuál es el objetivo del mismo, principalmente qué issues son los que vais a tratar
2. La lista de comprobación

Cuando paséis esa lista de comrpobación y veáis si os falta algo (o no), lo vemos de nuevo.

2024-03-04 19:42 UTC, JJ requested changes
¿Y desde donde se manejan todas estas clases? ¿Hay alguna *entidad*?
Finalmente, todos los módulos en Python, ¿qué fichero deben incluir obligatoriamente?

2024-03-04 19:42 UTC, JJ commented on TurnoGen/Code.md
> +# New directory for uploading code
¿Seguís necesitando este fichero?

2024-03-04 19:42 UTC, JJ commented on is.yaml
> +entidad: src/Recordatorio.js
:arrow_up:

2024-03-05 08:11 UTC, lugaresdev commented on TurnoGen/Codigo.md
> +# Nuevo directorio para subir código
@JJ Totalmente de acuerdo. Queda hecha la eliminación del archivo Codigo.md

2024-03-05 08:21 UTC, lugaresdev commented
> > @JJ listo para revisión
> 
> En este cuerpo del PR tenéis que poner
> 
> 1. Cuál es el objetivo del mismo, principalmente qué issues son los que vais a tratar
> 2. La lista de comprobación
> 
> Cuando paséis esa lista de comrpobación y veáis si os falta algo (o no), lo vemos de nuevo.

@maguilerafr te paso la info para que lo puedas editar: 

En esta etapa **(Nivel 2)** hemos tenido como **objetivo** el de **modelar los principales elementos extraídos de las HU**, para que en las siguientes MS se pueda empezar a obtener un PMV útil.

* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-03-05 08:29 UTC, lugaresdev commented on is.yaml
> +entidad: src/Recordatorio.js
He actualizado la ruta de la entidad en base a lo que estamos creando se deduce que la entidad es employee.

2024-03-05 08:32 UTC, lugaresdev commented on src/Recordatorio.js
> +
Toda la razón @JJ no es de buenas practicas dejar archivos innecesarios en la estructura base del proyecto.  Procedo a eliminarlo.

2024-03-05 08:33 UTC, JJ commented
> > > @JJ listo para revisión
> > 
> > 
> > En este cuerpo del PR tenéis que poner
> > 
> > 1. Cuál es el objetivo del mismo, principalmente qué issues son los que vais a tratar
> > 2. La lista de comprobación
> > 
> > Cuando paséis esa lista de comrpobación y veáis si os falta algo (o no), lo vemos de nuevo.
> 
> @maguilerafr te paso la info para que lo puedas editar:
> 
> En esta etapa **(Nivel 2)** hemos tenido como **objetivo** el de **modelar los principales elementos extraídos de las HU**, para que en las siguientes MS se pueda empezar a obtener un PMV útil.
> 
>     * [ ]  ¿Los issues que ha planteado la persona son efectivamente problemas y
>       evidencian comprensión de las historias de usuario? Si no es así, es mejor que
>       se le transmita antes de que empiece a crear cualquier código erróneo.
> 
>     * [ ]  ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
>       comprobación?
> 
>     * [ ]  ¿El código creado es una modelización válida de las historias de usuario
>       creadas por ti, y te sirve como base para programar la lógica de negocio?
> 
>     * [ ]  ¿El código creado sigue las mejores prácticas para el lenguaje de
>       programación que hayáis consensuado, tanto en identificadores, como
>       nombres de ficheros, como disposición de los diferentes ficheros en el
>       repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
>       aportan código para resolver el problema planteado en el mismo?
> 
>     * [ ]  ¿He comprobado que el código compile, o que quien lo ha programado ha lo
>       ha hecho y documentado en el repositorio?
> 
>     * [ ]  ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
>       correspondiente, que será el primero?
> 
>     * [ ]  ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
>       el objetivo 4 para poder programar la lógica de negocio?
> 
>     * [ ]  En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
>       directamente en el siguiente milestone, que incluye la lógica de negocio?

Por favor, *en el cuerpo*, no en un comentario.

2024-03-05 08:40 UTC, lugaresdev commented
> > > > @JJ listo para revisión
> > > 
> > > 
> > > En este cuerpo del PR tenéis que poner
> > > 
> > > 1. Cuál es el objetivo del mismo, principalmente qué issues son los que vais a tratar
> > > 2. La lista de comprobación
> > > 
> > > Cuando paséis esa lista de comrpobación y veáis si os falta algo (o no), lo vemos de nuevo.
> > 
> > 
> > @maguilerafr te paso la info para que lo puedas editar:
> > En esta etapa **(Nivel 2)** hemos tenido como **objetivo** el de **modelar los principales elementos extraídos de las HU**, para que en las siguientes MS se pueda empezar a obtener un PMV útil.
> > ```
> > * [ ]  ¿Los issues que ha planteado la persona son efectivamente problemas y
> >   evidencian comprensión de las historias de usuario? Si no es así, es mejor que
> >   se le transmita antes de que empiece a crear cualquier código erróneo.
> > 
> > * [ ]  ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
> >   comprobación?
> > 
> > * [ ]  ¿El código creado es una modelización válida de las historias de usuario
> >   creadas por ti, y te sirve como base para programar la lógica de negocio?
> > 
> > * [ ]  ¿El código creado sigue las mejores prácticas para el lenguaje de
> >   programación que hayáis consensuado, tanto en identificadores, como
> >   nombres de ficheros, como disposición de los diferentes ficheros en el
> >   repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
> >   aportan código para resolver el problema planteado en el mismo?
> > 
> > * [ ]  ¿He comprobado que el código compile, o que quien lo ha programado ha lo
> >   ha hecho y documentado en el repositorio?
> > 
> > * [ ]  ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
> >   correspondiente, que será el primero?
> > 
> > * [ ]  ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
> >   el objetivo 4 para poder programar la lógica de negocio?
> > 
> > * [ ]  En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
> >   directamente en el siguiente milestone, que incluye la lógica de negocio?
> > ```
> 
> Por favor, _en el cuerpo_, no en un comentario.

@JJ lo sé. El comentario es para que @maguilerafr que es quien puede editar el cuerpo del pullrequest lo haga cuando pueda y tenga la información a mano (en este caso en un comentario) para que pueda copiarlo al cuerpo del pullrequest. No te agobies :P

2024-03-05 08:48 UTC, JJ commented
> > > > > @JJ listo para revisión
> > > > 
> > > > 
> > > > En este cuerpo del PR tenéis que poner
> > > > 
> > > > 1. Cuál es el objetivo del mismo, principalmente qué issues son los que vais a tratar
> > > > 2. La lista de comprobación
> > > > 
> > > > Cuando paséis esa lista de comrpobación y veáis si os falta algo (o no), lo vemos de nuevo.
> > > 
> > > 
> > > @maguilerafr te paso la info para que lo puedas editar:
> > > En esta etapa **(Nivel 2)** hemos tenido como **objetivo** el de **modelar los principales elementos extraídos de las HU**, para que en las siguientes MS se pueda empezar a obtener un PMV útil.
> > > ```
> > > * [ ]  ¿Los issues que ha planteado la persona son efectivamente problemas y
> > >   evidencian comprensión de las historias de usuario? Si no es así, es mejor que
> > >   se le transmita antes de que empiece a crear cualquier código erróneo.
> > > 
> > > * [ ]  ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
> > >   comprobación?
> > > 
> > > * [ ]  ¿El código creado es una modelización válida de las historias de usuario
> > >   creadas por ti, y te sirve como base para programar la lógica de negocio?
> > > 
> > > * [ ]  ¿El código creado sigue las mejores prácticas para el lenguaje de
> > >   programación que hayáis consensuado, tanto en identificadores, como
> > >   nombres de ficheros, como disposición de los diferentes ficheros en el
> > >   repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
> > >   aportan código para resolver el problema planteado en el mismo?
> > > 
> > > * [ ]  ¿He comprobado que el código compile, o que quien lo ha programado ha lo
> > >   ha hecho y documentado en el repositorio?
> > > 
> > > * [ ]  ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
> > >   correspondiente, que será el primero?
> > > 
> > > * [ ]  ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
> > >   el objetivo 4 para poder programar la lógica de negocio?
> > > 
> > > * [ ]  En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
> > >   directamente en el siguiente milestone, que incluye la lógica de negocio?
> > > ```
> > 
> > 
> > Por favor, _en el cuerpo_, no en un comentario.
> 
> @JJ lo sé. El comentario es para que @maguilerafr que es quien puede editar el cuerpo del pullrequest lo haga cuando pueda y tenga la información a mano (en este caso en un comentario) para que pueda copiarlo al cuerpo del pullrequest. No te agobies :P

Es que estoy recibiendo mensajes a saco... En todo caso, ¿no te parece que hacerlo para que @maguilerafr lo copie duplica el trabajo? (Por no mencionar que me involucra a mi y a todo el que también recibe notificaciones)

2024-03-05 09:51 UTC, lugaresdev commented
@JJ Menuda fiesta con las notificaciones, entiendo a que te refiere. Pero que si en el primer mensaje ves que te referencio a ti en base de un mensaje de sugerencias y cambios pero el mensaje es para lolo para que lo tenga en cuenta y lo ponga en practica... JJ déjalo fluir como agua de rio que llega al mar, que ya caerá cada parte en su lugar. ;) Pero si contestas ese mensaje diciendo que eso no va ahí va en el cuerpo del pullrequest y yo te respondo después pues eso la fiesta de las notificaciones. jajajaja También es verdad que lo podría a ver solucionado yo desde un primer momento, mandando un mensaje por el grupo de trabajo del telegram justo como he hecho aquí pero en telegram si solo agregando a Manuel. Disculpa por la  fiesta de notificaciones y Gracias por que con estos ejemplos aprendemos haciendo.

2024-03-05 15:46 UTC, JJ commented
### En esta etapa (Nivel 2) hemos tenido como objetivo el de modelar los principales elementos extraídos de las HU1 e HU2, para que en las siguientes MS se pueda empezar a obtener un PMV útil.


> * [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?

En #13 habla de un "restaurante", es decir, un establecimiento que tendrá una serie de características, personal y horarios. Por otro lado, *domain driven design* habla de "entidades", es decir, clases que contienen estructuras de datos complejas. ¿Créis que efectivamente habéis incluido una entidad en vuestro código que represente "restaurante"? ¿Habéis abierto un issue que lo haga?

> * [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?

¿Cómo lo habéis comprobado?

> * [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio? 

En la barra que indica el progreso del milestone a la derecha parece que está a la mitad. ¿Qué representan el resto de los issues?

> * [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?


¿Cómo lo haríais, si no tenéis representación del "restaurante"?

2024-03-05 15:52 UTC, JJ commented
Os he actualizado el cuerpo del PR para que volváis a pasar la lista de comprobación. No se trata de que lo marquéis todo, sino de que sirva de guía para saber si todo está correcto y se puede avanzar.

2024-03-05 17:18 UTC, JJ requested changes
¿Por qué necesitaría María tener un calendario con meses con un número de días incorrectos?

2024-03-05 17:18 UTC, JJ commented on TurnoGen/annual_calendar.py
> +        self.months = [Month(name="Month " + str(i), num_days=30) for i in range(1, 13)]
¿Cuantos meses salen de esto? ¿Todos los meses tienen 30 días?

2024-03-05 19:39 UTC, JJ commented
Todavía tenéis una serie de comentarios en este PR que tendréis que solucionar. Convendría que creárais un issue para cada uno, y lo asignárais a personas diferentes.

2024-03-05 19:41 UTC, JJ requested changes
Algún comentario adicional para hacer...

2024-03-05 19:41 UTC, JJ commented on TurnoGen/weekly_schedule.py
> +class Week:
El nombre de esta clase no se corresponde con el del fichero.

2024-03-05 19:41 UTC, JJ commented on is.yaml
> +entidad: TurnoGen\employee.py
En general se usa la convención "Linux/MacOS" con la barra de separación de directorios en la otra dirección.

2024-03-05 19:41 UTC, JJ commented on TurnoGen/restaurant.py
> +class Restaurant:
Te he dicho que te lo compraba *como estaba*, no que estuviera completo...

2024-03-07 17:22 UTC, JJ commented
Errores de sintaxis encontrados:
```txt
poetry run pyflakes TurnoGen/*.py
TurnoGen/week.py:25:22: undefined name 'date'
```

2024-03-07 19:41 UTC, ZazRX8 approved these changes

2024-03-07 19:41 UTC, merged

2024-03-07 19:41 UTC, Patacabra approved these changes