Generar horas día
Codecr-ft/TurnoGen pull request #38
Opened 2024-02-22 19:04 UTC by maguilerafr

Con esta primera función he querido generar una estructura del día que genere en base a las horas de apertura del negocio (de 11h a 24h) los segmentos de las horas en los que poder asentar los turnos a posteriori.

2024-02-22 19:07 UTC, JJ commented
1. Todos los PRs tienen que estar asignados a un milestone
2. Siempre tienen que referirse a uno o varios issue, explicados en el cuerpo
3. Pero lo más importante es que no hay nada en el milestone 0 o PMV inicial que pida una función. Cualquier cosa que sea una función no tendría cabida dentro de este PMV.

2024-02-22 19:08 UTC, JJ requested changes
... y el fichero está vación.
Entiendo que es lo que me has enseñado, y por tanto no sería una función; así que quizá sea cuestión de ajustar la descripción de lo que estáshaciendo, y no el código en sí.

2024-02-22 19:09 UTC, JJ commented
Tampoco creo que el fichero deba llamarse #35, ¿no?

2024-02-22 19:17 UTC, JJ requested changes
Los nombres de fichero tienen su importancia...

2024-02-22 19:17 UTC, JJ commented on App/#35.py
> +class Dia:
¿Seguro que la mejor forma de llamar a un fichero es con el nombre del issue que sirve para crearlo? ¿No habrá una convención un poco más formal en Python como por ejemplo llamarlo con el nombre de la clase que contiene, pero en minúsculas?

2024-02-22 19:17 UTC, maguilerafr commented
> Tampoco creo que el fichero deba llamarse #35, ¿no?

Acabo de actualizar el PR.:
- Lo he asignado al MS0
- Ya he mencionado en el cuerpo del PR al issue al que va referido, que antes solo lo había puesto en el título.
- No termino de entender a que se refiere con lo que el MS0 no pida una función.
- Ya he adjuntado el contenido en el fichero, que he tenido un error al subirlo.
- Hemos acordado en el grupo que cada uno cree un fichero con el nombre de la issue en la que está trabajando, por eso el fichero se llama #35

2024-02-22 19:19 UTC, JJ commented
> > Tampoco creo que el fichero deba llamarse #35, ¿no?
> 
> Acabo de actualizar el PR.:
> 
> * Lo he asignado al MS0
> * Ya he mencionado en el cuerpo del PR al issue al que va referido, que antes solo lo había puesto en el título.
> * No termino de entender a que se refiere con lo que el MS0 no pida una función.

En la versión anterior sin código se describía como una función.

> * Hemos acordado en el grupo que cada uno cree un fichero con el nombre de la issue en la que está trabajando, por eso el fichero se llama [Turno #35](https://github.com/Codecr-ft/TurnoGen/issues/35)

No parece que eso sea una buena práctica. En la denominación de los ficheros (y directorios) tenéis que seguir las convenciones habituales en el lenguaje en el que estáis trabajando. Eso reduce la carga cognitiva, al poder saber fácilmente el contenido de un fichero sólo mirando el nombre.

2024-02-22 19:20 UTC, maguilerafr commented on App/#35.py
> +class Dia:
Vamos a darle una vuelta con el resto del grupo y vemos proponemos una mejor forma de llamar al archivo

2024-02-23 08:26 UTC, JJ requested changes
Una de las cosas a las que tenéis que acostumbraros es a usar *siempre* los mensajes de commit para documentar el código. Como os he comentado, estos mensajes de commit deben mencionar el issue con el que se trabaja y explicar la decisión tomada. En este caso no lo has hecho en uno, y sí en otro, pero aparentemente por casualidad, porque estaba en el nombre del fichero (incorrecto, como ya hemos comentado). Por otro lado, el que aparezca ese mensaje como "Update xxx" indica que estáis usando el formulario de GitHub en vez de la línea de órdenes, algo que he desaconsejado usar a este nivel.
Todas esas buenas prácticas no son capricho, sino que son parte de la ingeniería que hace que se pueda trabajar de forma más eficiente. Trabajar desde la línea de órdenes te obliga, por ejemplo, a escribir un mensaje de commit en vez de confiar en el que se incluye por omisión; también, por supuesto, a trabajar con varios ficheros a la vez si es necesario, y a usar `git commit -a` cuando se modifican varios fichero simultáneamente. El  uso de otros comandos como `git mv` (para cambiar nombre de ficheros) sólo se puede hacer desde línea de órdenes.
Si un código no sigue las buenas prácticas, lo más razonable es borrarlo. Sin embargo, en este caso, dado que es de los primeros que tengo la oportunidad de revisar, me gustaría pararme un poco en cómo se ha creado el código y si corresponde o no a lo que se buscaba; afortunadamente, sí se han respetado las buenas prácticas y está muy claro con qué issue estamos trabajando: el #35.
Este issue dice:

> Hemos detectado que María tiene serios problemas para asignar un **turno** a cada empleado, por lo que necesitamos definir con ella qué/cuáles son los **turnos** y el **rango** de horas que tiene cada turno que garantice un reparto equilibrado y eficiente para el buen funcionamiento del local.

Hago énfasis en dos de las palabras que aparecen en ese issue, que además se llama así, *Turno*. Eso no se menciona en este código, sino que se llama la clase Dia, el horario de apertura parece fijo (implícito en la línea 6 del fichero) y el *rango* de horas, también una palabra importante, no aparece en el código.

Siendo así, es imposible responder a la pregunta "¿Este código resuelve el problema?" ¿Puede María definir cuales son los turnos? ¿Puede saber cuál es el rango de horas? No os he pedido que os leáis Domain Driven Design completo, pero sí lo básico, que es establecer el *lenguaje ubicuo*. ¿Ayuda este código a que la aplicación y María entiendan de la misma forma qué es un turno? ¿O el rango de horas? Si la respuesta es no, convendría que se comenzara desde el principio, atendiendo al issue, y que cuando se creara el fichero siguiera las buenas prácticas habituales en Python.

2024-02-23 08:26 UTC, JJ commented on App/#35.py
> +
Una de las cuestiones importantes en este milestone es que sólo se debe trabajar con datos; por lo tanto, las funciones definidas tienen sentido *sólo* si se van a llamar desde el constructor (`__init__`  es el constructor en Python)

2024-02-23 08:27 UTC, JJ commented
Adicionalmente, el #35 está en el milestone 1 y este PR en el milestone 0. Por favor, tratad de entender los milestones y qué función tienen en el desarrollo, cómo se va creando un producto mínimamente viable en cada uno y cómo es imprescindible que en cada etapa *se trabaje sólo en un milestone*.

2024-02-27 15:06 UTC, JJ commented
¿Qué ha pasado con este PR? ¿Podéis revisar el título del mismo también?

2024-02-27 15:55 UTC, maguilerafr commented
@JJ revise los cambios cuando pueda

2024-02-27 15:55 UTC, JJ commented
No sé si habéis visto el objetivo del día: hacer bien los mensajes de commit. Los mensajes de commit:

1. Tienen una primera línea de como máximo 50 caracteres y que incluye siempre referencia a un issue.
2. Tiene el resto con 80 caracteres por línea
3. Explica por qué se ha tomado esa decisión, no qué se ha hecho (lo que se puede ver simplemente mirando qué cambios se han hecho)

También cambiad el título del PR a algo explicativo para todo el mundo. feat#35 no transmite cuál es el ámbito de este PR ni qué vamos a solucionar si se hace.

2024-02-27 16:08 UTC, JJ reviewed
¿El milestone 0 requere *herramientas* o solo modelos de datos?

2024-02-27 16:39 UTC, maguilerafr commented
> ¿El milestone 0 requere _herramientas_ o solo modelos de datos?

He vuelto a cambiar el código. Esta vez he generado un modelo de turno, no una herramienta, que sí cumple el MS0.

2024-02-27 16:50 UTC, JJ requested changes
Yo diría que tiene bastante buena pinta. Aunque has usado una función, es para generar una variable de instancia.

Ahora ¿crees que el nombre que tiene el fichero (y el directorio) sigue las mejores prácticas en Python?

2024-02-27 17:01 UTC, JJ commented
OK, que el resto @ZazRX8 o @ErikaVorozco si puede le den un vistazo a continuación.

2024-02-27 17:44 UTC, ZazRX8 approved these changes

2024-02-27 17:53 UTC, JJ commented
@ZazRX8 ¿lo apruebas con el nombre de fichero que tiene?

2024-02-27 17:57 UTC, ZazRX8 commented
> @ZazRX8 ¿lo apruebas con el nombre de fichero que tiene?

No va mal según mi vista. Solo hay que cambiar todo en minúscula si no estoy equivocando.

2024-02-27 17:59 UTC, JJ commented
> > @ZazRX8 ¿lo apruebas con el nombre de fichero que tiene?
> 
> No va mal según mi vista. Solo hay que cambiar todo en minúscula si no estoy equivocando.

¿No tendrías que esperar a que efectivamente lo pusiera en minúscula?

2024-02-27 18:03 UTC, ZazRX8 commented
> > > @ZazRX8 ¿lo apruebas con el nombre de fichero que tiene?
> > 
> > 
> > No va mal según mi vista. Solo hay que cambiar todo en minúscula si no estoy equivocando.
> 
> ¿No tendrías que esperar a que efectivamente lo pusiera en minúscula?

Disculpa. En futuro estaré mas pendiente. Gracias.

2024-02-27 18:29 UTC, JJ commented
¿Veis lo que pasa por modificar las cosas en la web y en local?

2024-02-27 18:30 UTC, maguilerafr commented
> ¿Veis lo que pasa por modificar las cosas en la web y en l

2024-02-27 18:33 UTC, JJ approved these changes
👍

2024-02-27 18:33 UTC, JJ commented on TurnoGen/turno.py
> +            raise ValueError("Tipo de jornada no válido")
Generalmente los mensajes de error deben contener datos sobre qué es lo que ha producido el error, por ejemplo, en este caso, `type_workday`.
También es una buena práctica crear tipos específicos para errores, de donde se pueda extraer con el programa información.
Conviene también que [leáis buenas prácticas sobre manejo de excepciones](https://reviewnprep.com/blog/mastering-exception-handling-in-python-real-life-examples-and-best-practices/). En general, si hay una posibilidad de que se lance una excepción, debes capturarla, si no el programa revienta. A nivel superior (en este caso el constructor) normalmente se relanza la excepción, pero de otro tipo.
No es que sea imprescindible, pero en un buen modelo de datos también hay "custom exceptions" como [explica aquí](https://www.linkedin.com/pulse/effective-error-handling-python-navigating-best-practices-patel-cnlje/)

2024-02-27 18:41 UTC, JJ commented on TurnoGen/turno.py
> +            raise ValueError("Tipo de jornada no válido, escriba 'completa' o 'partida'.")
```suggestion
            raise ValueError(f"Tipo de jornada {self.type_workday} no válido, escriba 'completa' o 'partida'.")
```

2024-02-27 18:47 UTC, maguilerafr commented on TurnoGen/turno.py
> +            raise ValueError("Tipo de jornada no válido, escriba 'completa' o 'partida'.")
Genial, gracias. Lo sumo.

2024-02-27 18:51 UTC, JJ commented
Yo ya lo he aprobado, ya es cosa vuestra. Cuando haya suficiente número de aprobaciones, se fusiona.

2024-02-27 18:57 UTC, merged