Feat#53 Completar el código en el archivo Restaurant.py
Codecr-ft/TurnoGen pull request #56
Opened 2024-03-06 16:23 UTC by lugaresdev

# Describe your changes
Este código **agrega** los **métodos** **_add_employee_**, **_remove_employee_** y **_update_employee_** para agregar, eliminar y actualizar empleados, respectivamente. Luego, se proporciona un ejemplo de cómo usar estos métodos para interactuar con la lista de empleados del restaurante.

## Issue ticket number and link
closes #53

## Checklist before requesting a review
- [x] I have performed a self-review of my code

2024-03-06 16:23 UTC, lugaresdev commented
@JJ Revisa esto.

2024-03-06 16:25 UTC, JJ commented
Conviene que pongáis los números de issue en la primera línea de los mensajes de commit, así es más fácil comprobarlo desde el principio.

2024-03-06 16:28 UTC, JJ reviewed
Aparte, ¿un restaurante tiene solo empleados? ¿No tiene algo más? ¿Turnos? ¿Horario de apertura? Si no es aquí, ¿dónde pensáis meterlo?

2024-03-06 16:28 UTC, JJ commented on TurnoGen/restaurant.py
> +        self.employees = employees or []
Una de las reglas fijas en programación orientada a objetos es que el objeto creado debe ser siempre correcto. ¿Sería correcto un restaurante con 0 empleados? ¿Es razonable el valor por omisión que habéis puesto arriba?

2024-03-06 16:28 UTC, JJ commented on TurnoGen/restaurant.py
> +    def add_employee(self, employee):
¿Se solicitan funciones en este milestone? ¿O sólo los datos?

2024-03-06 16:28 UTC, JJ commented on TurnoGen/restaurant.py
> +    def update_employee(self, old_employee, new_employee):
No se solicitan funciones, pero si se solicitaran, tendrían que hacerse sólo y exclusivamente los que pidiera la HU. En particular, ¿cuando se echa a un empleado se mete a otro automáticamente?

2024-03-06 16:28 UTC, JJ commented on TurnoGen/restaurant.py
> +# Ejemplo de uso
No se solicitan ejemplos de uso en este milestone. A ver si le decís a ChatGPT que no se enrolle más de lo estrictamente necesario.

2024-03-06 18:09 UTC, JJ commented on TurnoGen/restaurant.py
> +    def update_employee(self, old_employee, new_employee):
Ídem, ¿lo habéis cambiado?

2024-03-06 18:10 UTC, JJ commented
@lugaresdev ya hice la revisión, ¿habéis hecho algo sobre los comentarios?

2024-03-06 18:16 UTC, JJ commented
.... mirad los comenarios antes de aprobarlo, ¿no?

2024-03-06 19:22 UTC, JJ requested changes
¿Tendrá el restaurante alguna cosa aparte de los empleados?

2024-03-06 19:22 UTC, JJ commented on TurnoGen/restaurant.py
> +    def __init__(self, employees=[]):
¿De veras que cambiar None por `[]` cambia algo?

2024-03-06 19:22 UTC, JJ commented on TurnoGen/restaurant.py
> -        self.employees = employees if employees is not None and len(employees) > 0 else ["Empleado por defecto"]
A ver, lo que os decía de que no se pueden generar objetos incorrectos sigue aplicándose. Tendrías que seguir comprobando que la longitud del array no es cero.

2024-03-06 19:22 UTC, JJ commented on TurnoGen/restaurant.py
> +if __name__ == "__main__":
¿Esto no lo habías borrado?

2024-03-07 11:20 UTC, JJ requested changes
De veras, tratad de usar ChatGPT (o lo que uséis) sólo cuando sepáis con mucha precisión qué vais a hacer. Si le pedís que reescriba cosas acaba escribiendo un montón de cosas innecesarias que me cuesta a mi más trabajo revisar que a ChatGPT escribir.

2024-03-07 11:20 UTC, JJ commented on TurnoGen/restaurant.py
> +    def add_employee(self, contract_type, labor_responsibility, shift_management_ability, email):
Te recuerdo que la "lógica" no forma parte de este milestone.

2024-03-07 11:20 UTC, JJ commented on TurnoGen/restaurant.py
> +    def update_employee(self, old_employee, new_employee):
... y ya te lo dije aquí.

2024-03-07 16:38 UTC, JJ requested changes
Por favor, reaccionad a *todos* los comentarios antes de solicitar revisión de nuevo. Y también tratad de revisarlo antes entre vosotros.

2024-03-07 16:38 UTC, JJ commented on TurnoGen/restaurant.py
> +    def add_employee(self, employee):
Y las funciones siguen aquí.

2024-03-07 16:59 UTC, Lolic3 commented on TurnoGen/restaurant.py
> +    def update_employee(self, old_employee, new_employee):
Hemos borrado todas las funciones de la clase restaurant.

2024-03-07 16:59 UTC, Lolic3 commented on TurnoGen/restaurant.py
> +# Ejemplo de uso
Hemos borrado todos los ejemplos de uso.

2024-03-07 17:01 UTC, Lolic3 commented on TurnoGen/restaurant.py
> +    def __init__(self, employees=[]):
Esto ya no esta implementado en el codigo

2024-03-07 17:01 UTC, Lolic3 commented on TurnoGen/restaurant.py
> -        self.employees = employees if employees is not None and len(employees) > 0 else ["Empleado por defecto"]
Esto ya no esta implementado en el codigo.

2024-03-07 17:02 UTC, Lolic3 commented on TurnoGen/restaurant.py
> +if __name__ == "__main__":
Si no estaba borrado, ahora si lo esta

2024-03-07 17:02 UTC, Lolic3 commented on TurnoGen/restaurant.py
> +    def add_employee(self, contract_type, labor_responsibility, shift_management_ability, email):
Hemos borrado toda logica posible del codigo de restaurant

2024-03-07 17:08 UTC, JJ reviewed
¿Por qué se le pasa las horas de apertura pero no los empleados y los turnos? ¿Un restaurante se puede abrir sin saber qué empleados tiene ni qué turnos?

2024-03-07 17:08 UTC, JJ commented on TurnoGen/restaurant.py
> +        self.shifts = []
Como os he dicho arriba, cuando se crea un objeto tiene que estar en un estado válido. ¿Un restaurante sin nombre, sin turnos y empleados estaría en un estado válido?

2024-03-07 18:08 UTC, Patacabra approved these changes

2024-03-07 18:18 UTC, JJ approved these changes
Yo voy a aprobar también, ya que he escuchado a @ZazRX8

2024-03-07 18:23 UTC, ZazRX8 commented
> Yo voy a aprobar también, ya que he escuchado a @ZazRX8

Esto en plan que si ya esta echo para hacer revisión de trabajo. :))))

2024-03-07 18:26 UTC, lugaresdev commented
![image](https://github.com/Codecr-ft/TurnoGen/assets/122262868/25c6d023-0561-4b98-9c53-ca471ef06826)

2024-03-07 19:39 UTC, merged